name: Mutation Test CI
on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true
jobs:
  mutation-test:
    uses: reusable-workflows/blob/main/.github/workflows/mutation.yml@main
